// BITS 2_Max AND Pair
// Success rate: 34.23%
// Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair(arri, arrj) from the array such that i != j.

// Input Format:
// The first line contains size of array.
// Second line contains the elements of the array.

// Output Format:
// Output the required integer.

// Constraints:
// 1 <= N <= 10^5
// 1 <= arr[i] <= 10^5
import java.util.*;

public class lect2_2_Max_AND_Pair {
    public static void main(String[] args) {
        Scanner scn = new Scanner(System.in);

        int n = scn.nextInt();
        int[] arr = new int[n];

        for (int i = 0; i < n; i++) {
            arr[i] = scn.nextInt();
        }

        int ans = MaxANDPair(n, arr);
        System.out.println(ans);
    }

    public static int MaxANDPair(int n, int[] arr) {
        for (int bit = 31; bit >= 0; bit--) {
            int count = 0;

            for (int j = 0; j < n; j++) {
                if ((arr[j] & (1 << bit)) != 0) {
                    count++;
                }
            }

            if (count >= 2) {
                for (int j = 0; j < n; j++) {
                    if ((arr[j] & (1 << bit)) == 0) {
                        arr[j] = 0;
                    }
                }
            }
        }

        int first = -1, second = -1;

        for (int num : arr) {
            if (num != 0) {
                if (first == -1) first = num;
                else {
                    second = num;
                    break;
                }
            }
        }

        return first & second;
    }
}