// BITS 2_Max AND Pair
// Success rate: 34.23%
// Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair(arri, arrj) from the array such that i != j.

// Input Format:
// The first line contains size of array.
// Second line contains the elements of the array.

// Output Format:
// Output the required integer.

// Constraints:
// 1 <= N <= 10^5
// 1 <= arr[i] <= 10^5